-- ============================================================
--   CAR PARK MANAGEMENT SYSTEM - DATABASE
--   DBMS Lab Experiment
-- ============================================================

CREATE DATABASE IF NOT EXISTS CARPARK;
USE CARPARK;

-- TABLE 1: PARKING_SLOTS
CREATE TABLE PARKING_SLOTS (
    SLOTNO   INT PRIMARY KEY,
    SLOTTYPE VARCHAR(20) NOT NULL,
    STATUS   VARCHAR(10) DEFAULT 'FREE'
);

-- TABLE 2: RESIDENTS
CREATE TABLE RESIDENTS (
    REGNO   VARCHAR(15) PRIMARY KEY,
    OWNNAME VARCHAR(50) NOT NULL,
    FLATNO  VARCHAR(10) NOT NULL,
    SLOTNO  INT,
    VTYPE   VARCHAR(50),
    FOREIGN KEY (SLOTNO) REFERENCES PARKING_SLOTS(SLOTNO)
);

-- TABLE 3: GUESTS
CREATE TABLE GUESTS (
    GUESTID INT AUTO_INCREMENT PRIMARY KEY,
    REGNO   VARCHAR(15) NOT NULL,
    GNAME   VARCHAR(50) NOT NULL,
    FLATNO  VARCHAR(10) NOT NULL,
    VTYPE   VARCHAR(50),
    ENTIME  DATETIME,
    EXTIME  DATETIME
);

-- TABLE 4: PAYMENT
CREATE TABLE PAYMENT (
    PAYID       INT AUTO_INCREMENT PRIMARY KEY,
    REGNO       VARCHAR(15) NOT NULL,
    GNAME       VARCHAR(50),
    DURATION_HR INT,
    AMOUNT      DECIMAL(8,2),
    PAYTIME     DATETIME
);

-- TABLE 5: COMPLAINTS
CREATE TABLE COMPLAINTS (
    COMPID    INT AUTO_INCREMENT PRIMARY KEY,
    REGNO     VARCHAR(15) NOT NULL,
    COMPLAINT VARCHAR(200) NOT NULL,
    COMPDATE  DATETIME
);

-- ============================================================
-- SAMPLE DATA
-- ============================================================

INSERT INTO PARKING_SLOTS VALUES (1, 'Four-Wheeler', 'OCCUPIED');
INSERT INTO PARKING_SLOTS VALUES (2, 'Four-Wheeler', 'OCCUPIED');
INSERT INTO PARKING_SLOTS VALUES (3, 'Four-Wheeler', 'FREE');
INSERT INTO PARKING_SLOTS VALUES (4, 'Two-Wheeler',  'FREE');
INSERT INTO PARKING_SLOTS VALUES (5, 'Two-Wheeler',  'OCCUPIED');

INSERT INTO RESIDENTS VALUES ('TN10M3551', 'Vijay',  'P063', 1, 'ROLLS ROYCE GHOST');
INSERT INTO RESIDENTS VALUES ('TN10LM10',  'Lokesh', 'N121', 2, 'BMW 740i');
INSERT INTO RESIDENTS VALUES ('KL07AC123', 'Arun',   'A301', 5, 'Honda Activa');

INSERT INTO GUESTS (REGNO, GNAME, FLATNO, VTYPE, ENTIME, EXTIME)
VALUES ('TN10B055',  'Atlee',  'P063', 'RANGE ROVER', '2025-11-18 19:12:19', '2025-11-18 19:14:02');
INSERT INTO GUESTS (REGNO, GNAME, FLATNO, VTYPE, ENTIME, EXTIME)
VALUES ('KL05XY999', 'Ramesh', 'B202', 'Toyota Innova', '2025-11-18 10:00:00', '2025-11-18 12:30:00');

INSERT INTO PAYMENT (REGNO, GNAME, DURATION_HR, AMOUNT, PAYTIME)
VALUES ('TN10B055',  'Atlee',  1, 20.00, '2025-11-18 19:14:02');
INSERT INTO PAYMENT (REGNO, GNAME, DURATION_HR, AMOUNT, PAYTIME)
VALUES ('KL05XY999', 'Ramesh', 3, 60.00, '2025-11-18 12:30:00');

INSERT INTO COMPLAINTS (REGNO, COMPLAINT, COMPDATE)
VALUES ('TN10M3551', 'Someone parked in my slot', '2025-11-18 10:00:00');
INSERT INTO COMPLAINTS (REGNO, COMPLAINT, COMPDATE)
VALUES ('KL07AC123', 'Slot area not clean', '2025-11-19 09:00:00');

-- ============================================================
-- SQL QUERIES FOR LAB RECORD (not used in project)
-- ============================================================

-- SELECT ALL
SELECT * FROM RESIDENTS;
SELECT * FROM GUESTS;
SELECT * FROM PARKING_SLOTS;
SELECT * FROM PAYMENT;
SELECT * FROM COMPLAINTS;

-- SELECT with WHERE
SELECT * FROM RESIDENTS WHERE FLATNO = 'P063';
SELECT * FROM PARKING_SLOTS WHERE STATUS = 'FREE';
SELECT * FROM GUESTS WHERE EXTIME IS NULL;

-- JOIN
SELECT G.REGNO, G.GNAME, G.ENTIME, G.EXTIME, P.DURATION_HR, P.AMOUNT
FROM GUESTS G
JOIN PAYMENT P ON G.REGNO = P.REGNO;

-- UPDATE
UPDATE RESIDENTS SET VTYPE = 'LEXUS LM350H' WHERE REGNO = 'TN10M3551';

-- DELETE
DELETE FROM COMPLAINTS WHERE COMPID = 1;

-- ============================================================
-- END
-- ============================================================
