-- ============================================================
--   CAR PARK MANAGEMENT SYSTEM - DATABASE
--   College DBMS Lab Experiment
-- ============================================================

CREATE DATABASE IF NOT EXISTS CARPARK;
USE CARPARK;

-- TABLE 1: PARKING_SLOTS (created first, others reference it)
CREATE TABLE PARKING_SLOTS (
    SLOTNO      INT PRIMARY KEY,
    SLOTTYPE    VARCHAR(20) NOT NULL,
    STATUS      VARCHAR(10) DEFAULT 'FREE'
);

-- TABLE 2: RESIDENTS
CREATE TABLE RESIDENTS (
    REGNO       VARCHAR(15) PRIMARY KEY,
    OWNNAME     VARCHAR(50) NOT NULL,
    FLATNO      VARCHAR(10) NOT NULL,
    SLOTNO      INT,
    VTYPE       VARCHAR(50),
    FOREIGN KEY (SLOTNO) REFERENCES PARKING_SLOTS(SLOTNO)
);

-- TABLE 3: GUESTS
CREATE TABLE GUESTS (
    GUESTID     INT AUTO_INCREMENT PRIMARY KEY,
    REGNO       VARCHAR(15) NOT NULL,
    GNAME       VARCHAR(50) NOT NULL,
    FLATNO      VARCHAR(10) NOT NULL,
    VTYPE       VARCHAR(50),
    ENTIME      DATETIME,
    EXTIME      DATETIME
);

-- TABLE 4: VEHICLES
CREATE TABLE VEHICLES (
    REGNO       VARCHAR(15) PRIMARY KEY,
    VMODEL      VARCHAR(50) NOT NULL,
    VCOLOR      VARCHAR(20),
    VOWNER      VARCHAR(50),
    VCAT        VARCHAR(20)
);

-- TABLE 5: PAYMENT (fixed: removed broken foreign key)
CREATE TABLE PAYMENT (
    PAYID       INT AUTO_INCREMENT PRIMARY KEY,
    REGNO       VARCHAR(15) NOT NULL,
    GNAME       VARCHAR(50),
    DURATION_HR INT,
    AMOUNT      DECIMAL(8,2),
    PAYTIME     DATETIME
);

-- ============================================================
-- INSERT SAMPLE DATA
-- ============================================================

INSERT INTO PARKING_SLOTS VALUES (1, 'Four-Wheeler', 'OCCUPIED');
INSERT INTO PARKING_SLOTS VALUES (2, 'Four-Wheeler', 'OCCUPIED');
INSERT INTO PARKING_SLOTS VALUES (3, 'Four-Wheeler', 'FREE');
INSERT INTO PARKING_SLOTS VALUES (4, 'Two-Wheeler',  'FREE');
INSERT INTO PARKING_SLOTS VALUES (5, 'Two-Wheeler',  'OCCUPIED');

INSERT INTO RESIDENTS VALUES ('TN10M3551', 'Vijay',  'P063', 1, 'ROLLS ROYCE GHOST');
INSERT INTO RESIDENTS VALUES ('TN10LM10',  'Lokesh', 'N121', 2, 'BMW 740i');
INSERT INTO RESIDENTS VALUES ('KL07AC123', 'Arun',   'A301', 5, 'Honda Activa');

INSERT INTO GUESTS (REGNO, GNAME, FLATNO, VTYPE, ENTIME, EXTIME)
VALUES ('TN10B055',  'Atlee',  'P063', 'RANGE ROVER AUTOBIOGRAPHY', '2025-11-18 19:12:19', '2025-11-18 19:14:02');
INSERT INTO GUESTS (REGNO, GNAME, FLATNO, VTYPE, ENTIME, EXTIME)
VALUES ('KL05XY999', 'Ramesh', 'B202', 'Toyota Innova',             '2025-11-18 10:00:00', '2025-11-18 12:30:00');
INSERT INTO GUESTS (REGNO, GNAME, FLATNO, VTYPE, ENTIME, EXTIME)
VALUES ('TN22ZZ400', 'Priya',  'C105', 'Maruti Swift',              '2025-11-19 09:00:00', '2025-11-19 11:00:00');

INSERT INTO VEHICLES VALUES ('TN10M3551', 'ROLLS ROYCE GHOST',         'Black',  'Vijay',  'Resident');
INSERT INTO VEHICLES VALUES ('TN10LM10',  'BMW 740i',                  'White',  'Lokesh', 'Resident');
INSERT INTO VEHICLES VALUES ('KL07AC123', 'Honda Activa',              'Blue',   'Arun',   'Resident');
INSERT INTO VEHICLES VALUES ('TN10B055',  'RANGE ROVER AUTOBIOGRAPHY', 'Silver', 'Atlee',  'Guest');
INSERT INTO VEHICLES VALUES ('KL05XY999', 'Toyota Innova',             'White',  'Ramesh', 'Guest');

INSERT INTO PAYMENT (REGNO, GNAME, DURATION_HR, AMOUNT, PAYTIME)
VALUES ('TN10B055',  'Atlee',  1, 20.00, '2025-11-18 19:14:02');
INSERT INTO PAYMENT (REGNO, GNAME, DURATION_HR, AMOUNT, PAYTIME)
VALUES ('KL05XY999', 'Ramesh', 3, 60.00, '2025-11-18 12:30:00');
INSERT INTO PAYMENT (REGNO, GNAME, DURATION_HR, AMOUNT, PAYTIME)
VALUES ('TN22ZZ400', 'Priya',  2, 40.00, '2025-11-19 11:00:00');

-- ============================================================
-- SQL QUERIES (For Lab Record)
-- ============================================================

-- 1. SELECT ALL
SELECT * FROM RESIDENTS;
SELECT * FROM GUESTS;
SELECT * FROM PARKING_SLOTS;
SELECT * FROM VEHICLES;
SELECT * FROM PAYMENT;

-- 2. SELECT with WHERE
SELECT * FROM RESIDENTS WHERE FLATNO = 'P063';
SELECT * FROM GUESTS WHERE EXTIME IS NULL;
SELECT * FROM PARKING_SLOTS WHERE STATUS = 'FREE';

-- 3. JOIN
SELECT G.REGNO, G.GNAME, G.FLATNO, G.ENTIME, G.EXTIME,
       P.DURATION_HR, P.AMOUNT
FROM GUESTS G
JOIN PAYMENT P ON G.REGNO = P.REGNO;

-- 4. UPDATE
UPDATE RESIDENTS SET VTYPE = 'LEXUS LM350H' WHERE REGNO = 'TN10M3551';
UPDATE PARKING_SLOTS SET STATUS = 'FREE' WHERE SLOTNO = 3;

-- 5. DELETE
DELETE FROM GUESTS WHERE REGNO = 'TN22ZZ400';

-- ============================================================
-- END
-- ============================================================
